version: "3"
services:
  my-react-app:
    image: ananya21/my-react-app:latest
    stdin_open: true
    ports: 
      - "3002:80"
    networks:
      - mern-app
  backend:
    image: ananya21/backend:latest
    ports:
      - "5001:5001"
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local